name: vivelatarte
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.9252420137636364
  brandStrength: 0.2768020227085799
  lightness: 0.680804108036682
  brandColors:
    - '#F3F3F3'
    - '#49A2B2'
    - '#DEBF49'
    - '#F27D97'
    - '#F15B29'
  rhythmicContrast: 0.1190542585682124
typography_spectrum: 0.3261649
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 0.2831541
