name: vivelatarte
favicon: null
layout_spectrum: 0.3456669698935002
typography_spectrum: 0.2804943018127233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2768020227085799
  lightness: 0.680804108036682
  saturation: 0.9252420137636364
  rhythmicContrast: 0.11905425856821239
purpose: []
